# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('region', models.CharField(db_index=True, max_length=255, unique=True)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('default_role', models.CharField(max_length=255)),
                ('default_domain_id', models.CharField(max_length=255)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('api_version', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('created_at', models.DateField()),
                ('enabled', models.BooleanField(default=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
