# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Type'),
        ),
    ]
