# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20161204_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
