# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20161204_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
