"""empty message

Revision ID: 28f38d9e7724
Revises: 24ea14f8cb4e
Create Date: 2016-07-10 18:31:53.096426

"""

# revision identifiers, used by Alembic.
revision = '28f38d9e7724'
down_revision = '24ea14f8cb4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    ### end Alembic commands ###
