"""empty message

Revision ID: 48c96b4cae0c
Revises: 73982db0bb88
Create Date: 2016-08-31 21:53:02.488962

"""

# revision identifiers, used by Alembic.
revision = '48c96b4cae0c'
down_revision = '73982db0bb88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('default_role', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_providers_default_role'), 'providers', ['default_role'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_default_role'), table_name='providers')
    op.drop_column('providers', 'default_role')
    ### end Alembic commands ###
