"""empty message

Revision ID: 56c33e417a5c
Revises: ede7ee3212ad
Create Date: 2016-08-28 15:55:11.835537

"""

# revision identifiers, used by Alembic.
revision = '56c33e417a5c'
down_revision = 'ede7ee3212ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('x_session_token', sa.Text(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'x_session_token')
    ### end Alembic commands ###
