"""empty message

Revision ID: 5cc72c718d14
Revises: ad5c9cae2c6d
Create Date: 2016-08-24 22:56:39.588007

"""

# revision identifiers, used by Alembic.
revision = '5cc72c718d14'
down_revision = 'ad5c9cae2c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspended', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended')
    ### end Alembic commands ###
