"""empty message

Revision ID: 611ebee9c39b
Revises: 48c96b4cae0c
Create Date: 2016-10-16 14:35:50.504023

"""

# revision identifiers, used by Alembic.
revision = '611ebee9c39b'
down_revision = '48c96b4cae0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'providers', ['selected_provider_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'selected_provider_id')
    ### end Alembic commands ###
