"""empty message

Revision ID: 73982db0bb88
Revises: ad4bacc19155
Create Date: 2016-08-28 21:51:42.194149

"""

# revision identifiers, used by Alembic.
revision = '73982db0bb88'
down_revision = 'ad4bacc19155'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('region', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_providers_region'), 'providers', ['region'], unique=False)
    op.drop_column('providers', 'x_subject_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('x_subject_token', mysql.TEXT(collation=u'utf8_bin'), nullable=True))
    op.drop_index(op.f('ix_providers_region'), table_name='providers')
    op.drop_column('providers', 'region')
    ### end Alembic commands ###
