"""empty message

Revision ID: 8491b2bf3af9
Revises: 2db95cb9bcc9
Create Date: 2016-07-09 22:49:27.082441

"""

# revision identifiers, used by Alembic.
revision = '8491b2bf3af9'
down_revision = '2db95cb9bcc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_users_avatar'), 'users', ['avatar'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_avatar'), table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
