"""empty message

Revision ID: ad4bacc19155
Revises: 56c33e417a5c
Create Date: 2016-08-28 16:08:23.350311

"""

# revision identifiers, used by Alembic.
revision = 'ad4bacc19155'
down_revision = '56c33e417a5c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('x_subject_token', sa.Text(length=255), nullable=True))
    op.drop_column('providers', 'x_session_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('x_session_token', mysql.TEXT(collation=u'utf8_bin'), nullable=True))
    op.drop_column('providers', 'x_subject_token')
    ### end Alembic commands ###
