"""empty message

Revision ID: ad5c9cae2c6d
Revises: 070b614d54f1
Create Date: 2016-08-07 18:16:57.701675

"""

# revision identifiers, used by Alembic.
revision = 'ad5c9cae2c6d'
down_revision = '070b614d54f1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
