"""empty message

Revision ID: ede7ee3212ad
Revises: 2b52e8261507
Create Date: 2016-08-27 17:38:36.769787

"""

# revision identifiers, used by Alembic.
revision = 'ede7ee3212ad'
down_revision = '2b52e8261507'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('project_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_providers_project_name'), 'providers', ['project_name'], unique=False)
    op.drop_index('ix_providers_tenant_name', table_name='providers')
    op.drop_column('providers', 'tenant_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('tenant_name', mysql.VARCHAR(collation=u'utf8_bin', length=128), nullable=True))
    op.create_index('ix_providers_tenant_name', 'providers', ['tenant_name'], unique=False)
    op.drop_index(op.f('ix_providers_project_name'), table_name='providers')
    op.drop_column('providers', 'project_name')
    ### end Alembic commands ###
