# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to='static/avatar/%Y-%m-%d'),
        ),
    ]
