# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20161210_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
